#Server info...
---
server:
  port: 8085
---
management:
  port: 8081
---
spring:
  profiles: dev

  datasource:
    username: exampleuser
    password: changeme
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database:5432/exampledb
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
---
spring:
  profiles: integration

  datasource:
    username: SA
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
