#Server info...
---
server:
  port: 8085
---
management:
  port: 8081
---
#Here's our Dev server profile.
spring:
  profiles: dev

  datasource:
    username: exampleuser
    password: changeme
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database:5432/exampledb
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
---
#This profile is used for integration tests, when we're only running this Spring Boot application.  We still need a
#database to point to for any integration tests that require one to be present.  This serves that purpose perfectly.
spring:
  profiles: integration

  datasource:
    username: SA
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
