version: "3.1"

services:
  database:
    image: purpleowl/example-application-db
    user: postgres
    ports:
      - "5432:5432"

  appserver:
    image: purpleowl/example-application-data
    user: gordon
    ports:
      - "8081:8081"
      - "8080:8080"