version: "3.1"

services:
  database:
    container_name: database
    image: 172.16.118.137:5000/example-application-db:BLOG-POST-1
    user: postgres
    ports:
      - "5432:5432"
    networks:
      - backend

  data-service:
    container_name: data-service
    image: 172.16.118.137:5000/example-application-data:BLOG-POST-1
    ports:
      - "8081:8081"
      - "8085:8085"
    networks:
      - backend

networks:
  backend: